#!/bin/bash
function download_mp3(){
  cd $PROJECT_PATH/youtube_to_mp3
  ./download_mp3.py $@
  cd -
  #mv ~/repos/youtube_to_mp3/*.mp3 /storage/3366-3031/Music/Downloads/
  mv $PROJECT_PATH/youtube_to_mp3/*.mp3 /sdcard/Music/
}

function keep_my_phone_awake(){
  ping -i 0.3 localhost
}

function backup_my_termux(){
  cd ~
  gpg -c . --passphrase "1234"
  cd - 
}

function ssh_my_host(){
  ssh xyu@$host_ip
}

alias cqlsh='sourcepython;cqlsh --cqlversion=3.4.4'
export termux_settings="$PROJECT_PATH/termux_related"

# check if need to update host
if [ -f  ~/.config/misc/host_ip ]; then
  update_host_info
fi

# if ! $(ps aux |grep sshd);then
#   echo "no sshd found"
#   echo  "$(ps aux |grep sshd)"
# else
#   echo "found sshd"
# fi

export TEMP_PATH=~/temp
